### ISSUE TITLE
我都没看到懂怎么用，大神来看一下

### ISSUE THREAD

**Issue by leakl** [whistle-plugins/whistle.vase#1]
![image](https://user-images.githubusercontent.com/2120476/34512623-a1a70f7a-f09e-11e7-946a-68fd9f6b94e5.png)
![image](https://user-images.githubusercontent.com/2120476/34512641-ae307b6e-f09e-11e7-95fe-347f2e73c968.png)
![image](https://user-images.githubusercontent.com/2120476/34512662-c5b41c46-f09e-11e7-87d5-a35ab84675b9.png)

为什么输出不是JSON?

**Comment by avwo** [comment]
这个是`content-type`问题，看下这个：[几点说明](https://github.com/whistle-plugins/whistle.vase#几点说明)

**Comment by leakl** [comment]
谢谢大神，终于可以正常请求了json ，但新的问题又来怎么 使用mock 语法呢，直接写吗？好像不行
用render 好像也不行
![image](https://user-images.githubusercontent.com/2120476/34514223-508a7664-f0a7-11e7-942b-360116899957.png)

**Comment by avwo** [comment]
创建时要选 `Script` 才能用 `out` 和 `render`

**Comment by Ghostdar** [comment]
所以怎么使用mock语法？还是不明白
