### ISSUE TITLE
有没有办法使用mockjs的同时，根据req.body的某些值，对mockjs返回结果再设置值呢？

### ISSUE THREAD

**Issue by flytam** [whistle-plugins/whistle.vase#16]
![image](https://user-images.githubusercontent.com/20512530/90478297-8a7fde80-e15f-11ea-98f9-e6a2f8a591b4.png)
实现类似这样的效果。campaign.json 是一个mockjs的模版内容

**Comment by avwo** [comment]
https://github.com/whistle-plugins/whistle.vase#mergejson--jsonn

**Comment by flytam** [comment]
![image](https://user-images.githubusercontent.com/20512530/90479259-f44cb800-e160-11ea-84b6-157e504d5b6c.png)
这样子写吗？好像后面那个会覆盖前面的。不是深合并
```
out(merge( json(render('campaign.json' )), {
	data: {
    	pagination: {
        	page: req.body.page,
          page_count: 20
        }
    }
}  ))
```

**Comment by avwo** [comment]
@echopi 有空帮忙看下merge引入extend等模块支持下深度合并

**Comment by avwo** [comment]
重新安装最新版本 `v1.3.1`:
``` txt
// 深度合并
merge(true, ...);
```
