### ISSUE TITLE
请问, 如果使用 file函数 , 那么 如何 获取 whistle中 Files中的 文件文本呢?

### ISSUE THREAD

**Issue by bugaio** [whistle-plugins/whistle.vase#17]
请问, 如果使用 file函数 , 那么 如何 获取 whistle中 Files中的 文件文本呢?

**Comment by avwo** [comment]
规则里面配这个路径，whistle会自动读取 
![image](https://user-images.githubusercontent.com/11450939/91965872-abd9f080-ed43-11ea-9d72-badc296bc11e.png)
