### ISSUE TITLE
Unkown protocol 

### ISSUE THREAD

**Issue by diguazai** [whistle-plugins/whistle.vase#4]
在rules 里面配置了 /baidu.com/ vase://mock 也在vase新建了mock，但是我访问百度首页的时候报了一个
“Unkown protocol vase” 的错误，inspect 插件也一样

**Comment by avwo** [comment]
插件安装了没，有没有启用

**Comment by diguazai** [comment]
安装了，插件列表vase的状态也是勾选的

**Comment by avwo** [comment]
我这边试了没问题，`whistle.inspect` 的配置看READEM

**Comment by diguazai** [comment]
一会儿到公司上截图你看看
