### ISSUE TITLE
有没有支持注释的计划？

### ISSUE THREAD

**Issue by xinconan** [whistle-plugins/whistle.vase#8]
现在会把输入的内容全部返回，想在里面加点注释，会把注释也一并返回

**Comment by avwo** [comment]
哪块输入的内容

**Comment by avwo** [comment]
我看看

**Comment by avwo** [comment]
@xinconan 可以根据类型注释，如：html 可以用 `<!-- xxx -->`，script 可以用js的注释等等

**Comment by xinconan** [comment]
试过，可以注释，忘了之前怎么设置的了。
如果能支持快捷键注释就更好了

**Comment by avwo** [comment]
可以，后续会对这个插件做一些升级，到时加上快捷操作

**Comment by xinconan** [comment]
> 可以，后续会对这个插件做一些升级，到时加上快捷操作

期待
